name: Build and publish

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    #- name: Install Saxon, Ant and Python
    #  run: |
    #    apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
    #    ./shellscripts/script.sh
    #    pip install -r requirements.txt
    #- name: Build
    #  run: |
    #    ant build-full-edition
    #- name: Update Favicons
    #  run: python update_favicons.py
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './html'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html
